#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

if [ -d $ELC_DRUPAL_MOUNT ]; then
	mv /var/www/html /var/www/html.backup
	ln -sf $ELC_DRUPAL_MOUNT/drupal-7.9 /var/www/html
	ln -sf $ELC_DRUPAL_MOUNT/test /var/www/html/test
	chown -R www-data:www-data var/www/html
fi

exec "$@"
